# Configs for pwills.com

title: Kimba SABI N'GOYE
email: kimbasabingoye@gmail.com
name: "Kimba SABI N'GOYE"
url: https://kimbasabingoye.github.io/
repository: "kimbasabingoye/kimbasabingoye.github.io"
twitter_username: kimbasabingoye
github_username: kimbasabingoye

include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"
# Outputting
permalink: /:categories/:title/
timezone: Europe/Paris

# settings for author profile
author:
  name: "Kimba SABI N'GOYE"
  avatar: "/assets/images/bio-photo.png"
  bio: "Result-oriented Software Development Engineer with a strong interest in building scalable data systems and applications."
  location: "Paris, France"
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/kimbasabingoye"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kimbasabingoye"

# # comments by disqus
comments:
  provider: "disqus"
  disqus:
    shortname: "kimbasabingoye"

github: [metadata]

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-0S5FW31NN6"
    anonymize_ip: false # default

footer:
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/kimbasabingoye"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kimbasabingoye"

# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      path: ""
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
