FROM ruby:3.2.6-alpine3.20

RUN apk add --no-cache build-base gcc libc-dev make git nodejs npm bash tzdata yaml-dev

ENV LANG=C.UTF-8 GEM_HOME="/usr/local/bundle" PATH="$GEM_HOME/bin:$PATH"

WORKDIR /site

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

EXPOSE 4000

CMD ["bundle", "exec", "jekyll", "serve", "--host", "0.0.0.0", "--watch"]
