FROM ruby:3.2.6-alpine3.20 AS builder

RUN apk add --no-cache build-base gcc libc-dev make git bash yaml-dev

ENV LANG=C.UTF-8 GEM_HOME="/usr/local/bundle" PATH="$GEM_HOME/bin:$PATH"

WORKDIR /site

COPY Gemfile Gemfile.lock /site/

RUN bundle install

COPY . .

RUN bundle exec jekyll build

FROM nginx:alpine

COPY --from=builder /site/_site /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
